// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

/*
Package goserver is a generated protocol buffer package.

It is generated from these files:
	server.proto

It has these top-level messages:
	Empty
	Alive
	MoteRequest
	EmbeddedTest
	State
	ServerState
*/
package goserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContextType int32

const (
	ContextType_UNKNOWN ContextType = 0
	ContextType_REGULAR ContextType = 1
)

var ContextType_name = map[int32]string{
	0: "UNKNOWN",
	1: "REGULAR",
}
var ContextType_value = map[string]int32{
	"UNKNOWN": 0,
	"REGULAR": 1,
}

func (x ContextType) String() string {
	return proto.EnumName(ContextType_name, int32(x))
}
func (ContextType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Alive struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Alive) Reset()                    { *m = Alive{} }
func (m *Alive) String() string            { return proto.CompactTextString(m) }
func (*Alive) ProtoMessage()               {}
func (*Alive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Alive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MoteRequest struct {
	Master bool `protobuf:"varint,1,opt,name=master" json:"master,omitempty"`
}

func (m *MoteRequest) Reset()                    { *m = MoteRequest{} }
func (m *MoteRequest) String() string            { return proto.CompactTextString(m) }
func (*MoteRequest) ProtoMessage()               {}
func (*MoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MoteRequest) GetMaster() bool {
	if m != nil {
		return m.Master
	}
	return false
}

type EmbeddedTest struct {
	Blah *Alive `protobuf:"bytes,1,opt,name=blah" json:"blah,omitempty"`
	Test string `protobuf:"bytes,2,opt,name=test" json:"test,omitempty"`
}

func (m *EmbeddedTest) Reset()                    { *m = EmbeddedTest{} }
func (m *EmbeddedTest) String() string            { return proto.CompactTextString(m) }
func (*EmbeddedTest) ProtoMessage()               {}
func (*EmbeddedTest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EmbeddedTest) GetBlah() *Alive {
	if m != nil {
		return m.Blah
	}
	return nil
}

func (m *EmbeddedTest) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

type State struct {
	Key       string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	TimeValue int64  `protobuf:"varint,2,opt,name=time_value,json=timeValue" json:"time_value,omitempty"`
	Value     int64  `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Text      string `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *State) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *State) GetTimeValue() int64 {
	if m != nil {
		return m.TimeValue
	}
	return 0
}

func (m *State) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *State) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ServerState struct {
	States []*State `protobuf:"bytes,1,rep,name=states" json:"states,omitempty"`
}

func (m *ServerState) Reset()                    { *m = ServerState{} }
func (m *ServerState) String() string            { return proto.CompactTextString(m) }
func (*ServerState) ProtoMessage()               {}
func (*ServerState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServerState) GetStates() []*State {
	if m != nil {
		return m.States
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "goserver.Empty")
	proto.RegisterType((*Alive)(nil), "goserver.Alive")
	proto.RegisterType((*MoteRequest)(nil), "goserver.MoteRequest")
	proto.RegisterType((*EmbeddedTest)(nil), "goserver.EmbeddedTest")
	proto.RegisterType((*State)(nil), "goserver.State")
	proto.RegisterType((*ServerState)(nil), "goserver.ServerState")
	proto.RegisterEnum("goserver.ContextType", ContextType_name, ContextType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoserverService service

type GoserverServiceClient interface {
	IsAlive(ctx context.Context, in *Alive, opts ...grpc.CallOption) (*Alive, error)
	Mote(ctx context.Context, in *MoteRequest, opts ...grpc.CallOption) (*Empty, error)
	State(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerState, error)
}

type goserverServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoserverServiceClient(cc *grpc.ClientConn) GoserverServiceClient {
	return &goserverServiceClient{cc}
}

func (c *goserverServiceClient) IsAlive(ctx context.Context, in *Alive, opts ...grpc.CallOption) (*Alive, error) {
	out := new(Alive)
	err := grpc.Invoke(ctx, "/goserver.goserverService/IsAlive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goserverServiceClient) Mote(ctx context.Context, in *MoteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/goserver.goserverService/Mote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goserverServiceClient) State(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerState, error) {
	out := new(ServerState)
	err := grpc.Invoke(ctx, "/goserver.goserverService/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoserverService service

type GoserverServiceServer interface {
	IsAlive(context.Context, *Alive) (*Alive, error)
	Mote(context.Context, *MoteRequest) (*Empty, error)
	State(context.Context, *Empty) (*ServerState, error)
}

func RegisterGoserverServiceServer(s *grpc.Server, srv GoserverServiceServer) {
	s.RegisterService(&_GoserverService_serviceDesc, srv)
}

func _GoserverService_IsAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoserverServiceServer).IsAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goserver.goserverService/IsAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoserverServiceServer).IsAlive(ctx, req.(*Alive))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoserverService_Mote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoserverServiceServer).Mote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goserver.goserverService/Mote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoserverServiceServer).Mote(ctx, req.(*MoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoserverService_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoserverServiceServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goserver.goserverService/State",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoserverServiceServer).State(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoserverService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goserver.goserverService",
	HandlerType: (*GoserverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAlive",
			Handler:    _GoserverService_IsAlive_Handler,
		},
		{
			MethodName: "Mote",
			Handler:    _GoserverService_Mote_Handler,
		},
		{
			MethodName: "State",
			Handler:    _GoserverService_State_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xdf, 0x4a, 0xeb, 0x40,
	0x10, 0xc6, 0x93, 0x93, 0xa4, 0x7f, 0x26, 0x85, 0x96, 0xe5, 0x28, 0xa1, 0x22, 0x94, 0x15, 0xa9,
	0x08, 0x16, 0xad, 0xe0, 0x7d, 0x91, 0x52, 0x44, 0xad, 0xb0, 0x6d, 0xf5, 0x52, 0x12, 0x3b, 0x68,
	0xb1, 0x69, 0x6a, 0x76, 0x5a, 0xda, 0x07, 0xf2, 0x3d, 0x65, 0x77, 0x13, 0x8c, 0xb9, 0x9b, 0x99,
	0x6f, 0x76, 0x7e, 0x93, 0x6f, 0x02, 0x0d, 0x89, 0xe9, 0x16, 0xd3, 0xde, 0x3a, 0x4d, 0x28, 0x61,
	0xb5, 0xf7, 0xc4, 0xe4, 0xbc, 0x0a, 0xde, 0x30, 0x5e, 0xd3, 0x9e, 0x1f, 0x81, 0x37, 0x58, 0x2e,
	0xb6, 0xc8, 0x18, 0xb8, 0xab, 0x30, 0xc6, 0xc0, 0xee, 0xd8, 0x67, 0x75, 0xa1, 0x63, 0x7e, 0x0a,
	0xfe, 0x63, 0x42, 0x28, 0xf0, 0x6b, 0x83, 0x92, 0xd8, 0x21, 0x54, 0xe2, 0x50, 0x12, 0xa6, 0xba,
	0xa9, 0x26, 0xb2, 0x8c, 0x8f, 0xa0, 0x31, 0x8c, 0x23, 0x9c, 0xcf, 0x71, 0x3e, 0x55, 0x7d, 0x27,
	0xe0, 0x46, 0xcb, 0xf0, 0x43, 0x77, 0xf9, 0xfd, 0x66, 0x2f, 0xa7, 0xf6, 0x34, 0x49, 0x68, 0x51,
	0xf1, 0x08, 0x25, 0x05, 0xff, 0x0c, 0x4f, 0xc5, 0x3c, 0x02, 0x6f, 0x42, 0x21, 0x21, 0x6b, 0x81,
	0xf3, 0x89, 0xfb, 0x6c, 0x17, 0x15, 0xb2, 0x63, 0x00, 0x5a, 0xc4, 0xf8, 0xba, 0x0d, 0x97, 0x1b,
	0xd4, 0x8f, 0x1c, 0x51, 0x57, 0x95, 0x67, 0x55, 0x60, 0xff, 0xc1, 0x33, 0x8a, 0xa3, 0x15, 0x93,
	0x18, 0xc6, 0x8e, 0x02, 0x37, 0x67, 0xec, 0x88, 0xdf, 0x80, 0x3f, 0xd1, 0xdb, 0x18, 0x52, 0x17,
	0x2a, 0x52, 0x05, 0x32, 0xb0, 0x3b, 0xce, 0xdf, 0x6d, 0x75, 0x83, 0xc8, 0xe4, 0xf3, 0x2e, 0xf8,
	0xb7, 0xc9, 0x4a, 0x8d, 0x98, 0xee, 0xd7, 0xc8, 0x7c, 0xa8, 0xce, 0xc6, 0xf7, 0xe3, 0xa7, 0x97,
	0x71, 0xcb, 0x52, 0x89, 0x18, 0x8e, 0x66, 0x0f, 0x03, 0xd1, 0xb2, 0xfb, 0xdf, 0x36, 0x34, 0xf3,
	0x19, 0x8a, 0xb4, 0x78, 0x43, 0x76, 0x01, 0xd5, 0x3b, 0x69, 0x7c, 0x2e, 0xdb, 0xd1, 0x2e, 0x17,
	0xb8, 0xc5, 0x2e, 0xc1, 0x55, 0xbe, 0xb3, 0x83, 0x5f, 0xa9, 0x70, 0x87, 0xe2, 0x0b, 0x73, 0x44,
	0x8b, 0x5d, 0xe5, 0xce, 0x95, 0xb5, 0x76, 0x61, 0x46, 0xe1, 0xbb, 0xb9, 0x15, 0x55, 0xf4, 0x3f,
	0x71, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x80, 0xf5, 0x34, 0x66, 0x23, 0x02, 0x00, 0x00,
}
